org.gradle.jvmargs=-Xmx1536m -Xms256m -Xss512k -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=192m -XX:ActiveProcessorCount=4 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.vfs.watch=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
