// lib/models/grammar_curriculum.dart

class GrammarChapter {
  final String title;
  final String description; // 상위 카테고리 (e.g., 'Unit 01 문장의 종류')
  final List<String> details;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GrammarChapter &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description;

  @override
  int get hashCode => title.hashCode ^ description.hashCode;

  const GrammarChapter({required this.title, required this.description, this.details = const []});
}

class GrammarCategory {
  final String title;
  final String description;
  final List<GrammarChapter> chapters;

  const GrammarCategory({required this.title, required this.description, required this.chapters});
}

const List<GrammarCategory> grammarCurriculum = [
  GrammarCategory(
    title: '중학교 영문법',
    description: '기초 다지기: 영어 문장의 기본 구조를 이해하고, 기초적인 시제와 품사의 활용법을 익힙니다.',
    chapters: [
      GrammarChapter(title: 'be동사의 현재형과 과거형', description: 'be동사'),
      GrammarChapter(title: 'be동사의 부정문과 의문문', description: 'be동사'),
      GrammarChapter(title: '일반동사의 현재형', description: '일반동사'),
      GrammarChapter(title: '일반동사의 과거형', description: '일반동사'),
      GrammarChapter(title: '일반동사의 부정문', description: '일반동사'),
      GrammarChapter(title: '일반동사의 의문문', description: '일반동사'),
      GrammarChapter(title: 'can, may', description: '조동사'),
      GrammarChapter(title: 'must, have to, should', description: '조동사'),
      GrammarChapter(title: '진행형', description: '진행형과 미래시제'),
      GrammarChapter(title: 'will, be going to', description: '진행형과 미래시제'),
      GrammarChapter(title: '감정동사 + 형용사', description: '동사의 종류'),
      GrammarChapter(title: '목적어가 두 개 필요한 동사', description: '동사의 종류'),
      GrammarChapter(title: '목적어 보어가 필요한 동사', description: '동사의 종류'),
      GrammarChapter(title: '셀 수 있는 명사 vs. 셀 수 없는 명사', description: '명사와 관사'),
      GrammarChapter(title: '관사', description: '명사와 관사'),
      GrammarChapter(title: '인칭대명사, 재귀대명사', description: '대명사'),
      GrammarChapter(title: 'this, that, it', description: '대명사'),
      GrammarChapter(title: 'one, some, any', description: '대명사'),
      GrammarChapter(title: '형용사', description: '형용사와 부사'),
      GrammarChapter(title: '부사', description: '형용사와 부사'),
      GrammarChapter(title: '원급, 비교급, 최상급', description: '형용사와 부사'),
      GrammarChapter(title: 'to부정사의 명사적 용법', description: 'to부정사와 동명사'),
      GrammarChapter(title: 'to부정사의 형용사적, 부사적 용법', description: 'to부정사와 동명사'),
      GrammarChapter(title: '동명사의 역할', description: 'to부정사와 동명사'),
      GrammarChapter(title: '장소를 나타내는 전치사', description: '전치사'),
      GrammarChapter(title: '시간을 나타내는 전치사', description: '전치사'),
      GrammarChapter(title: '기타 전치사', description: '전치사'),
      GrammarChapter(title: 'and, but, or, so', description: '접속사'),
      GrammarChapter(title: 'when, before, after, until', description: '접속사'),
      GrammarChapter(title: 'because, if, that', description: '접속사'),
      GrammarChapter(title: '의문사 who, what, which', description: '의문문, 명령문, 감탄문'),
      GrammarChapter(title: '의문사 when, where, why, how', description: '의문문, 명령문, 감탄문'),
      GrammarChapter(title: '부가의문문', description: '의문문, 명령문, 감탄문'),
      GrammarChapter(title: '부정의문문, 선택의문문', description: '의문문, 명령문, 감탄문'),
      GrammarChapter(title: '명령문, 감탄문', description: '의문문, 명령문, 감탄문'),
      GrammarChapter(title: '감정동사 + 수여동사', description: '여러 가지 동사'),
      GrammarChapter(title: '목적격 보어를 가지는 동사', description: '여러 가지 동사'),
      GrammarChapter(title: '현재, 과거, 미래시제 / 진행형', description: '시제'),
      GrammarChapter(title: '완료시제', description: '시제'),
      GrammarChapter(title: 'can, may, will', description: '조동사'),
      GrammarChapter(title: 'would like to, had better, used to', description: '조동사'),
      GrammarChapter(title: '명사적 용법의 to부정사', description: 'to부정사'),
      GrammarChapter(title: '형용사적 용법, 부사적 용법의 to부정사', description: 'to부정사'),
      GrammarChapter(title: 'to부정사의 의미상의 주어, 시제, 태', description: 'to부정사'),
      GrammarChapter(title: '목적격 보어로 쓰이는 to부정사', description: 'to부정사'),
      GrammarChapter(title: 'to부정사 구문, 독립부정사', description: 'to부정사'),
      GrammarChapter(title: '동명사의 쓰임', description: '동명사'),
      GrammarChapter(title: '동명사와 to부정사', description: '동명사'),
      GrammarChapter(title: '현재분사 vs. 과거분사', description: '분사'),
      GrammarChapter(title: '분사구문', description: '분사'),
      GrammarChapter(title: '능동태와 수동태', description: '수동태'),
      GrammarChapter(title: '수동태의 여러 가지 형태', description: '수동태'),
      GrammarChapter(title: '주의해야 할 수동태', description: '수동태'),
      GrammarChapter(title: '부정대명사', description: '대명사'),
      GrammarChapter(title: '재귀대명사', description: '대명사'),
      GrammarChapter(title: '비교 구문을 이용한 표현', description: '비교'),
      GrammarChapter(title: '시간, 이유, 결과의 접속사', description: '접속사'),
      GrammarChapter(title: '조건, 양보의 접속사 / 명령문 + and, or ~', description: '접속사'),
      GrammarChapter(title: '관계대명사', description: '관계사'),
      GrammarChapter(title: '관계대명사 that, what / 관계대명사의 생략', description: '관계사'),
      GrammarChapter(title: '관계부사', description: '관계사'),
      GrammarChapter(title: '가정법 과거, 가정법 과거완료', description: '가정법'),
      GrammarChapter(title: 'I wish ~ 가정법, as if + 가정법', description: '가정법'),
      GrammarChapter(title: '시제의 일치', description: '일치와 화법'),
      GrammarChapter(title: '화법', description: '일치와 화법'),
      GrammarChapter(title: '현재완료', description: '시제'),
      GrammarChapter(title: '과거완료, 미래완료', description: '시제'),
      GrammarChapter(title: 'had better, ought to, used to, 조동사 + have + ed', description: '조동사'),
      GrammarChapter(title: '4형식, 5형식 문장의 수동태', description: '수동태'),
      GrammarChapter(title: '명사적 용법의 to부정사', description: '부정사'),
      GrammarChapter(title: '형용사적 용법, 부사적 용법의 to부정사', description: '부정사'),
      GrammarChapter(title: '목적격 보어로 쓰이는 부정사', description: '부정사'),
      GrammarChapter(title: '동명사의 역할', description: '동명사'),
      GrammarChapter(title: '동명사 vs. to부정사', description: '동명사'),
      GrammarChapter(title: '여러 가지 분사구문', description: '분사'),
      GrammarChapter(title: '여러 가지 비교구문', description: '비교'),
      GrammarChapter(title: '종속 접속사', description: '접속사'),
      GrammarChapter(title: '짝으로 이루어진 접속사, 간접의문문', description: '접속사'),
      GrammarChapter(title: '주의해야 할 관계사', description: '관계사'),
      GrammarChapter(title: '복합관계사', description: '관계사'),
      GrammarChapter(title: '가정법 과거, 가정법 과거완료, 혼합 가정법', description: '가정법'),
      GrammarChapter(title: 'I wish, as if, It’s time + 가정법', description: '가정법'),
      GrammarChapter(title: '주의해야 할 가정법', description: '가정법'),
      GrammarChapter(title: '수의 일치', description: '일치와 화법'),
      GrammarChapter(title: '강조, 부정구문, 병렬', description: '기타 구문'),
      GrammarChapter(title: '도치, 생략, 동격', description: '기타 구문'),
    ],
  ),
  GrammarCategory(
    title: '고등학교 영문법',
    description: '심화 및 확장: 복잡한 문장 구조를 이해하고, 준동사의 심화 용법 및 특수 구문을 학습합니다.',
    chapters: [
      GrammarChapter(title: '구의 정리', description: '문장의 이해'),
      GrammarChapter(title: '문장의 종류', description: '문장의 이해'),
      GrammarChapter(title: '1형식 문장 (S+V)', description: '문장의 이해'),
      GrammarChapter(title: '2형식 문장 (S+V+C)', description: '문장의 이해'),
      GrammarChapter(title: '3형식 문장 (S+V+O)', description: '문장의 이해'),
      GrammarChapter(title: '4형식 문장 (S+V+O+O₁)', description: '문장의 이해'),
      GrammarChapter(title: '5형식 문장 (S+V+O+C₁)', description: '문장의 이해'),
      GrammarChapter(title: '5형식 문장 (S+V+O+C₂)', description: '문장의 이해'),
      GrammarChapter(title: '현재시제·과거시제', description: '시제'),
      GrammarChapter(title: '미래시제', description: '시제'),
      GrammarChapter(title: '미래를 나타내는 현재시제·진행형', description: '시제'),
      GrammarChapter(title: '진행형', description: '시제'),
      GrammarChapter(title: '현재완료 (계속·경험)', description: '시제'),
      GrammarChapter(title: '현재완료 (완료·결과)', description: '시제'),
      GrammarChapter(title: '과거 vs. 완료표현', description: '시제'),
      GrammarChapter(title: '과거완료·미래완료·완료진행형', description: '시제'),
      GrammarChapter(title: 'can, be able to, could (능력·가능)', description: '조동사'),
      GrammarChapter(title: 'can, could (가능성·허가·요청)', description: '조동사'),
      GrammarChapter(title: 'may, might (추측·허가)', description: '조동사'),
      GrammarChapter(title: 'must, have to (의무·추측)', description: '조동사'),
      GrammarChapter(title: 'should, ought to (조언·의무)', description: '조동사'),
      GrammarChapter(title: 'had better, would rather (충고·선택)', description: '조동사'),
      GrammarChapter(title: 'used to, would (습관)', description: '조동사'),
      GrammarChapter(title: '조동사 + have p.p.', description: '조동사'),
      GrammarChapter(title: '수동태의 기본 개념', description: '수동태'),
      GrammarChapter(title: '4형식 문장의 수동태', description: '수동태'),
      GrammarChapter(title: '5형식 문장의 수동태', description: '수동태'),
      GrammarChapter(title: '동사의 시제와 수동태', description: '수동태'),
      GrammarChapter(title: '조동사와 수동태', description: '수동태'),
      GrammarChapter(title: 'by 이외의 전치사로 쓰는 수동태', description: '수동태'),
      GrammarChapter(title: 'to부정사의 명사적 용법: 주어·목적어·보어', description: '부정사'),
      GrammarChapter(title: 'to부정사의 형용사적 용법 / 명사 + to부정사', description: '부정사'),
      GrammarChapter(title: 'to부정사의 부사적 용법: 이유·결과·판단의 근거·감정의 원인', description: '부정사'),
      GrammarChapter(title: 'to부정사의 부사적 용법: 목적·원인·조건·형용사 + to부정사', description: '부정사'),
      GrammarChapter(title: 'to부정사의 시제·태', description: '부정사'),
      GrammarChapter(title: 'to부정사의 의미상 주어', description: '부정사'),
      GrammarChapter(title: '동사를 수식하는 부정사', description: '부정사'),
      GrammarChapter(title: 'too ~ to-v, enough to-v', description: '부정사'),
      GrammarChapter(title: '의문사 + to-v / what to-v', description: '부정사'),
      GrammarChapter(title: '부정사의 의미상 주어 + 수식', description: '부정사'),
      GrammarChapter(title: '동명사의 역할', description: '동명사'),
      GrammarChapter(title: '동명사 vs. to부정사', description: '동명사'),
      GrammarChapter(title: '전치사의 목적어로 쓰이는 동명사', description: '동명사'),
      GrammarChapter(title: '동명사와 의미상 주어', description: '동명사'),
      GrammarChapter(title: '동명사를 사용한 관용 구문', description: '동명사'),
      GrammarChapter(title: '분사의 쓰임', description: '분사'),
      GrammarChapter(title: '현재분사 vs. 과거분사', description: '분사'),
      GrammarChapter(title: '감정을 유발하는 v-ing vs. 감정을 느끼는 p.p.', description: '분사'),
      GrammarChapter(title: '분사의 의미상 주어', description: '분사'),
      GrammarChapter(title: '분사의 시제와 태', description: '분사'),
      GrammarChapter(title: '분사구문과의 의미적 관계', description: '분사'),
      GrammarChapter(title: '독립 분사구문', description: '분사'),
      GrammarChapter(title: '(with + (대)명사 + 분사) 구문', description: '분사'),
      GrammarChapter(title: '등위접속사', description: '접속사'),
      GrammarChapter(title: '상관접속사', description: '접속사'),
      GrammarChapter(title: '명사절을 이끄는 접속사 - that', description: '접속사'),
      GrammarChapter(title: '명사절을 이끄는 접속사 - if, whether', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (시간)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (이유)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (조건)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (양보)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (목적)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (비교)', description: '접속사'),
      GrammarChapter(title: '부사절을 이끄는 접속사 (V 기반)', description: '접속사'),
      GrammarChapter(title: '가정법 과거', description: '가정법'),
      GrammarChapter(title: '가정법 과거완료', description: '가정법'),
      GrammarChapter(title: '혼합가정법', description: '가정법'),
      GrammarChapter(title: '가정법 정리', description: '가정법'),
      GrammarChapter(title: 'I wish+가정법', description: '가정법'),
      GrammarChapter(title: 'as if + 가정법', description: '가정법'),
      GrammarChapter(title: '기타 가정법', description: '가정법'),
      GrammarChapter(title: '바람 / 희망 / 뒤따른 대용구', description: '가정법'),
      GrammarChapter(title: '주격 관계대명사', description: '관계사'),
      GrammarChapter(title: '목적격 관계대명사', description: '관계사'),
      GrammarChapter(title: '소유격 관계대명사', description: '관계사'),
      GrammarChapter(title: '관계대명사 that', description: '관계사'),
      GrammarChapter(title: '관계대명사와 전치사', description: '관계사'),
      GrammarChapter(title: '관계부사', description: '관계사'),
      GrammarChapter(title: '복합관계사', description: '관계사'),
      GrammarChapter(title: '관계사의 계속적 용법', description: '관계사'),
      GrammarChapter(title: '관계사의 생략', description: '관계사'),
      GrammarChapter(title: '셀 수 있는 명사 vs. 셀 수 없는 명사', description: '명사·관사·대명사'),
      GrammarChapter(title: '주의해야 하는 명사', description: '명사·관사·대명사'),
      GrammarChapter(title: '관사 정리', description: '명사·관사·대명사'),
      GrammarChapter(title: '소유격대명사·재귀대명사', description: '명사·관사·대명사'),
      GrammarChapter(title: '대명사 정리', description: '명사·관사·대명사'),
      GrammarChapter(title: '부정대명사', description: '명사·관사·대명사'),
      GrammarChapter(title: '형용사의 쓰임', description: '형용사·부사'),
      GrammarChapter(title: '형용사절', description: '형용사·부사'),
      GrammarChapter(title: '부사의 종류', description: '형용사·부사'),
      GrammarChapter(title: '부사의 위치', description: '형용사·부사'),
      GrammarChapter(title: '주의해야 할 부사', description: '형용사·부사'),
      GrammarChapter(title: '형용사·부사의 비교 변화', description: '비교'),
      GrammarChapter(title: '원급 표현', description: '비교'),
      GrammarChapter(title: '비교급 표현', description: '비교'),
      GrammarChapter(title: '최상급 표현', description: '비교'),
      GrammarChapter(title: '비교급 비교 표현 혼합', description: '비교'),
      GrammarChapter(title: '최상급 비교 표현 혼합', description: '비교'),
      GrammarChapter(title: '의문·비교급을 이용한 최상급 표현', description: '비교'),
      GrammarChapter(title: '전치사의 쓰임', description: '전치사'),
      GrammarChapter(title: '장소를 나타내는 전치사', description: '전치사'),
      GrammarChapter(title: '운동을 나타내는 전치사', description: '전치사'),
      GrammarChapter(title: '시간의 전치사', description: '전치사'),
      GrammarChapter(title: '시기의 전치사', description: '전치사'),
      GrammarChapter(title: '수단의 전치사', description: '전치사'),
      GrammarChapter(title: '목적의 전치사', description: '전치사'),
      GrammarChapter(title: '기타 전치사', description: '전치사'),
      GrammarChapter(title: '수의 일치', description: '일치·화법'),
      GrammarChapter(title: '수의 일치의 원칙', description: '일치·화법'),
      GrammarChapter(title: '시제 일치의 원칙', description: '일치·화법'),
      GrammarChapter(title: '화법의 전환 원칙', description: '일치·화법'),
      GrammarChapter(title: '시제와 관계된 전환', description: '일치·화법'),
      GrammarChapter(title: '의문문·명령문과 관련된 전환', description: '일치·화법'),
      GrammarChapter(title: '부정 표현', description: '특수 구문'),
      GrammarChapter(title: '도치', description: '특수 구문'),
      GrammarChapter(title: '강조', description: '특수 구문'),
      GrammarChapter(title: '생략', description: '특수 구문'),
    ],
  ),
  GrammarCategory(
    title: '토익(TOEIC) 영문법',
    description: '실용 및 문제 풀이 중심: 비즈니스 및 일상생활에서의 실용성에 초점을 맞추며, 정답을 빠르게 찾는 능력이 중요합니다.',
    chapters: [
      GrammarChapter(title: '주어와 동사 찾기 (수일치)', description: '문장의 구조'),
      GrammarChapter(title: '5형식 동사와 목적격 보어', description: '문장의 구조'),
      GrammarChapter(title: '가주어 it, 가목적어 it', description: '문장의 구조'),
      GrammarChapter(title: '능동태 vs. 수동태', description: '동사'),
      GrammarChapter(title: '문맥에 맞는 시제 선택 (단순/완료)', description: '동사'),
      GrammarChapter(title: '조동사의 종류와 쓰임', description: '동사'),
      GrammarChapter(title: '동사 자리 vs. 준동사 자리 구분', description: '준동사'),
      GrammarChapter(title: 'to부정사의 역할 (명사, 형용사, 부사)', description: '준동사'),
      GrammarChapter(title: '동명사의 역할 (주어, 목적어, 보어)', description: '준동사'),
      GrammarChapter(title: 'to부정사를 목적어로 취하는 동사', description: '준동사'),
      GrammarChapter(title: '동명사를 목적어로 취하는 동사', description: '준동사'),
      GrammarChapter(title: '분사의 역할 (명사 수식)', description: '준동사'),
      GrammarChapter(title: '감정 동사의 분사 (boring vs. bored)', description: '준동사'),
      GrammarChapter(title: '분사구문', description: '준동사'),
      GrammarChapter(title: '명사 자리 (관사/소유격 뒤, 전치사 목적어)', description: '품사'),
      GrammarChapter(title: '형용사 자리 (명사 수식, 보어)', description: '품사'),
      GrammarChapter(title: '부사 자리 (동사, 형용사, 부사, 문장 수식)', description: '품사'),
      GrammarChapter(title: '혼동하기 쉬운 형용사/부사 어휘', description: '품사'),
      GrammarChapter(title: '접속사 vs. 전치사 구분 (뒤에 오는 구조)', description: '접속사와 전치사'),
      GrammarChapter(title: '명사절 접속사 (that, whether, if, 의문사)', description: '접속사와 전치사'),
      GrammarChapter(title: '부사절 접속사 (시간, 이유, 조건, 양보)', description: '접속사와 전치사'),
      GrammarChapter(title: '상관접속사 (both, either, not only 등)', description: '접속사와 전치사'),
      GrammarChapter(title: '의미가 비슷한 접속사와 전치사 구분', description: '접속사와 전치사'),
      GrammarChapter(title: '관계대명사 (주격, 목적격, 소유격)', description: '관계사'),
      GrammarChapter(title: '관계부사 (where, when, why)', description: '관계사'),
      GrammarChapter(title: '관계대명사 that vs. what', description: '관계사'),
      GrammarChapter(title: '복합관계사 (whoever, whatever 등)', description: '관계사'),
      GrammarChapter(title: '인칭대명사의 격 (주격, 소유격, 목적격)', description: '대명사'),
      GrammarChapter(title: '재귀대명사의 용법 (재귀, 강조)', description: '대명사'),
      GrammarChapter(title: '지시대명사 that/those (후치 수식)', description: '대명사'),
      GrammarChapter(title: '부정대명사 (one, another, other 등)', description: '대명사'),
      GrammarChapter(title: '원급/비교급/최상급의 형태와 쓰임', description: '비교'),
      GrammarChapter(title: '비교급 강조 부사 (much, even, still, far, a lot)', description: '비교'),
      GrammarChapter(title: 'The + 비교급, The + 비교급', description: '비교'),
      GrammarChapter(title: '가정법 과거 / 과거완료', description: '가정법'),
      GrammarChapter(title: 'should/would/could/might + have p.p.', description: '가정법'),
      GrammarChapter(title: 'If의 생략 및 도치', description: '가정법'),
      GrammarChapter(title: '도치 (부정어, 장소/방향 부사구)', description: '특수 구문'),
      GrammarChapter(title: '병렬 구조', description: '특수 구문'),
      GrammarChapter(title: '강조 (It is ~ that)', description: '특수 구문'),
    ],
  ),
];
